# Generated by Django 5.0.2 on 2024-04-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_contracts_product"),
        ("customers", "0005_alter_customers_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.contracts"
            ),
        ),
    ]
