# Generated by Django 5.0.2 on 2024-04-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leads",
            unique_together={
                ("last_name", "first_name", "middle_name", "email", "phone")
            },
        ),
    ]
