# Generated by Django 5.0.2 on 2024-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contracts_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="file",
            field=models.FileField(default="", upload_to="contracts/%Y/%m/%d"),
        ),
    ]
