# Generated by Django 5.0.2 on 2024-04-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contracts_file"),
        ("products", "0002_alter_products_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.products",
                verbose_name="Услуга",
            ),
        ),
    ]
