# Generated by Django 5.0.2 on 2024-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0002_alter_advertise_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertise",
            name="promotion_channel",
            field=models.CharField(),
        ),
    ]
